// <auto-generated />
using System;
using Inkdrop_lite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inkdrop_lite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920150722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InkdropLite.Api.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Hash");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.ToTable("Attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachments_ContentLength", "\"ContentLength\" >= 0");
                        });
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotebookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pinned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SourceTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotebookId");

                    b.HasIndex("SourceTemplateId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("NotebookId", "UpdatedAt");

                    b.ToTable("Notes", t =>
                        {
                            t.HasCheckConstraint("CK_Notes_NotOwnTemplate", "\"SourceTemplateId\" IS NULL OR \"SourceTemplateId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Notebook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IconAttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconSvg")
                        .HasMaxLength(262144)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentNotebookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IconAttachmentId");

                    b.HasIndex("Name");

                    b.HasIndex("Order");

                    b.HasIndex("ParentNotebookId");

                    b.ToTable("Notebooks", t =>
                        {
                            t.HasCheckConstraint("CK_Notebooks_NotOwnParent", "\"ParentNotebookId\" IS NULL OR \"ParentNotebookId\" <> \"Id\"");
                        });
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NoteAttachment", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId", "AttachmentId");

                    b.HasIndex("AttachmentId");

                    b.ToTable("NoteAttachments", (string)null);
                });

            modelBuilder.Entity("NoteTag", b =>
                {
                    b.Property<Guid>("NoteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("NoteId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NoteTags", (string)null);
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Note", b =>
                {
                    b.HasOne("InkdropLite.Api.Models.Notebook", "Notebook")
                        .WithMany("Notes")
                        .HasForeignKey("NotebookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InkdropLite.Api.Models.Note", "SourceTemplate")
                        .WithMany("DerivedNotes")
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Notebook");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Notebook", b =>
                {
                    b.HasOne("InkdropLite.Api.Models.Attachment", "IconAttachment")
                        .WithMany("NotebooksUsingAsIcon")
                        .HasForeignKey("IconAttachmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InkdropLite.Api.Models.Notebook", "ParentNotebook")
                        .WithMany("ChildNotebooks")
                        .HasForeignKey("ParentNotebookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IconAttachment");

                    b.Navigation("ParentNotebook");
                });

            modelBuilder.Entity("NoteAttachment", b =>
                {
                    b.HasOne("InkdropLite.Api.Models.Attachment", null)
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkdropLite.Api.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NoteTag", b =>
                {
                    b.HasOne("InkdropLite.Api.Models.Note", null)
                        .WithMany()
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkdropLite.Api.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Attachment", b =>
                {
                    b.Navigation("NotebooksUsingAsIcon");
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Note", b =>
                {
                    b.Navigation("DerivedNotes");
                });

            modelBuilder.Entity("InkdropLite.Api.Models.Notebook", b =>
                {
                    b.Navigation("ChildNotebooks");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
